import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SettingsIcon from '@mui/icons-material/Settings';
import ListAltIcon from '@mui/icons-material/ListAlt';
import './globals.css';

import { MSWComponent } from '@/mocks/MSWComponent';
import ReactQueryProvider from '@/context/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: 추후 ui 개발 완료 후 border 제거
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="w-screen h-screen max-w-[540px] mx-auto">
          {/* 헤더 컴포넌트 분리 고려 */}
          <header className="flex justify-end border border-black-500">
            <ListAltIcon />
            <SettingsIcon />
          </header>

          <div className="min-h-[93%] p-4 border border-black-500">
            <MSWComponent>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </MSWComponent>
          </div>

          <footer className="min-h-[7%] border border-black-500">
            <nav>네브 아이콘 탭</nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
