import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen max-w-[540px] mx-auto">
          <div className="min-h-[93%] bg-orange-500">{children}</div>
          <footer className="min-h-[7%]  bg-cyan-600">footer</footer>
        </div>
      </body>
    </html>
  );
}
