import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>

      <body className={inter.className}>
        <div className="w-screen h-screen max-w-[540px] mx-auto">
          <div className="min-h-[93%] bg-orange-500 p-4">{children}</div>
          <footer className="min-h-[7%]  bg-cyan-600">
            <nav>네브 아이콘 탭</nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
